---
title: "twitteR02_Rohan_sentimentwc"
output: html_document
---



```{r}
library(httr)
library(tm)
library(wordcloud)
library(twitteR)
library(tm.plugin.webmining)
library(openNLP)
library(qdap)
library(slam)
library(RCurl)
library(rjson)
library(RJSONIO)
library(stringr)

oauth_endpoints("twitter")

#consumer_key ="your consumer key"
#consumer_secret="your consumer secret"
#access_token="your access token"
#access_token_secret="your access token secret"

setup_twitter_oauth(consumer_key,consumer_secret,access_token,access_token_secret)

#functions to clean the text.
clean.text <- function(some_txt)
{
  some_txt = gsub("(RT|via)((?:\b\\W*@\\w+)+)", "", some_txt)
  some_txt = gsub("@\\ww+", "", some_txt)
  some_txt = gsub("[[:punct:]]", "", some_txt)
  some_txt = gsub("[[:digit:]]", "", some_txt)
  some_txt = gsub("http\\w+", "", some_txt)
  some_txt = gsub("[ t]{2,}", "", some_txt)
  some_txt = gsub("^\\s+|\\s+$", "", some_txt)
  some_txt = gsub("amp", "", some_txt)
  # define "tolower error handling" function
  try.tolower = function(x)
  {
    y = NA
    try_error = tryCatch(tolower(x), error=function(e) e)
    if (!inherits(try_error, "error"))
      y = tolower(x)
    return(y)
  }
  some_txt = sapply(some_txt, try.tolower)
  some_txt = some_txt[some_txt != ""]
  names(some_txt) = NULL
  return(some_txt)
}
  
##get sentiment function
getSentiment <- function (text, key){
  
  text <- URLencode(text);
   #save all the spaces, then get rid of the weird characters that break the API, then convert back the URL-encoded spaces.
  text <- str_replace_all(text, "%20", " ");
  text <- str_replace_all(text, "%\\d\\d", "");
  text <- str_replace_all(text, " ", "%20");
  
  if (str_length(text) > 360){
    text <- substr(text, 0, 359);
  }
  ##########################################
   data <- getURL(paste("http://api.datumbox.com/1.0/TwitterSentimentAnalysis.json?api_key=", key, "&text=",text, sep=""))
   js <- fromJSON(data, asText=TRUE);
# get mood probability
  sentiment = js$output$result
 return(list(sentiment=sentiment))
}

##db_key from datumbox API
#db_key="26bd6503e3cc3d8eedd8be4a13c8b7b1"

#new
db_key="4342093b9bf2a77c7c7ea6ce386d35b3"
#get the tweets
tweets = searchTwitter("iphone", 100, lang="en") 

# get text
tweet_txt = sapply(tweets, function(x) x$getText())

# clean text
tweet_clean = clean.text(tweet_txt)
tweet_num = length(tweet_clean)


#create a dataframe
tweet_df = data.frame(text=tweet_clean, sentiment=rep("", tweet_num),stringsAsFactors=FALSE)


# apply function getSentiment
sentiment = rep(0, tweet_num)


for (i in 1:tweet_num)
{
  tmp = getSentiment(tweet_clean[i], db_key)
  tweet_df$sentiment[i] = tmp$sentiment
  #print(paste(i," of ", tweet_num))
  
}


tweet_df <- tweet_df[tweet_df$sentiment!="",]


#separate text by sentiment
sents = levels(factor(tweet_df$sentiment))

# get the labels and percents

labels <- lapply(sents, function(x) paste(x,format(round((length((tweet_df[tweet_df$sentiment ==x,])$text)/length(tweet_df$sentiment)*100),2),nsmall=2),"%"))

##create the so called docs for each category and add the tweet texts to these categories:
nemo = length(sents)
emo.docs = rep("", nemo)
for (i in 1:nemo)
{
  tmp = tweet_df[tweet_df$sentiment == sents[i],]$text
  
  emo.docs[i] = paste(tmp,collapse=" ")
}


# remove stopwords
emo.docs = removeWords(emo.docs, stopwords("german"))
emo.docs = removeWords(emo.docs, stopwords("english"))
corpus = Corpus(VectorSource(emo.docs))
tdm = TermDocumentMatrix(corpus)
tdm = as.matrix(tdm)
colnames(tdm) = labels

# comparison word cloud
comparison.cloud(tdm, colors = brewer.pal(nemo, "Dark2"),
                 scale = c(3,.5), random.order = FALSE, title.size = 1.5)




```



```{r, echo=FALSE}

```


